name: Create Release on Tag Push

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Environment Variables
      - name: Set Environment Variable
        run: |
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

        # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 8
          run_install: false

      # Get pnpm store directory
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Setup pnpm cache
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      - name: Extract version from plugin.json
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' plugin.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build for production, 这一步会生成一个 package.zip
      - name: Build for production
        run: pnpm build

      - name: Create release on Sentry
        run: |
          npx @sentry/cli releases new ${{ env.VERSION }} --project ${{ env.SENTRY_PROJECT }} --org ${{ env.SENTRY_ORG }}
          npx @sentry/cli releases files ${{ env.VERSION }} upload-sourcemaps ./dist --rewrite --project ${{ env.SENTRY_PROJECT }} --org ${{ env.SENTRY_ORG }}
          npx @sentry/cli releases finalize ${{ env.VERSION }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: paneon
          SENTRY_PROJECT: siyuan-database-properties-plugin

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "package.zip"
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
